document.writeln("<div id=\'warperHed\'> ");
document.writeln("  <!-- PC导航 -->");
document.writeln("  <div class=\'pc_nav\'>");
document.writeln("    <header class=\'header1 f-cb\'>");
document.writeln("      <div class=\'header-left f-cb\'>");
document.writeln("        <h1 class=\'logo\'> <a href=\'index.html\'> <img class=\'img1\' src=\'images/logo_03.png\' alt=\'logo\'> <img class=\'img2\' src=\'images/logo_03.png\' alt=\'logo\'> </a> </h1>");
document.writeln("        <nav class=\'fr\'>");
document.writeln("          <ul class=\'f-cb\'>");
document.writeln("            <li class=\'hvr-left subnav2 js-m js-m-2 animate\'> <a class=\'home-dec\' href=\'index.html\'>网站首页</a> ");
document.writeln("              <!-- 图标开始 --> ");
document.writeln("              <!-- 图标结束 --> ");
document.writeln("            </li>");
document.writeln("            <li class=\'hvr-left subnav2 js-m js-m-2 animate\'> <a class=\'home-dec\' href=\'about.html\'>学院概况</a> ");
document.writeln("              <!-- 图标开始 --> ");
document.writeln("              <i class=\'iconfont iconJt\'></i> ");
document.writeln("              <!-- 图标结束 -->");
document.writeln("              <div class=\'navSedBox\'>");
document.writeln("                <ul class=\'navSedUl\'>");
document.writeln("                  <li class=\'navYj\'> <i class=\'iconfont backBtn\'></i> 学院概况</li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'about.html\' class=\'navSedTitLink\'>简介</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'zuxzhijigou.html\' class=\'navSedTitLink\'>组织机构</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'guanliceng.html\' class=\'navSedTitLink\'>管理层</a> </h3>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'navContentBox\'>");
document.writeln("                  <div class=\'picBox\'> <img src=\'images/about.jpg\' title=\'\' class=\'navImg\' alt=\'关于我们\'> </div>");
document.writeln("                  <a href=\'/intro/1.html\' class=\'tit\'>关于我们</a>");
document.writeln("                  <article class=\'navSummray\'></article>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </li>");
document.writeln("            <li class=\'hvr-left subnav2 js-m js-m-2 animate\'> <a class=\'home-dec\' href=\'kecheng.html\'>教学课程</a> ");
document.writeln("              <!-- 图标开始 --> ");
document.writeln("              <i class=\'iconfont iconJt\'></i> ");
document.writeln("              <!-- 图标结束 -->");
document.writeln("              <div class=\'navSedBox\'>");
document.writeln("                <ul class=\'navSedUl\'>");
document.writeln("                  <li class=\'navYj\'> <i class=\'iconfont backBtn\'></i> 教学课程</li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'kechengWx.html\' class=\'navSedTitLink\'>文学</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'kechengLx.html\' class=\'navSedTitLink\'>理学</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'kechengwgyy.html\' class=\'navSedTitLink\'>外国语言</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'kechengZzx.html\' class=\'navSedTitLink\'>政治学</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'kechengJsjx.html\' class=\'navSedTitLink\'>计算机类</a> </h3>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'navContentBox\'>");
document.writeln("                  <div class=\'picBox\'> <img src=\'images/ktbg.jpg\' title=\'\' class=\'navImg\' alt=\'教学课程\'> </div>");
document.writeln("                  <a href=\'kecheng.html\' class=\'tit\'>教学课程</a>");
document.writeln("                  <article class=\'navSummray\'></article>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </li>");
document.writeln("            <li class=\'hvr-left subnav2 js-m js-m-2 animate\'> <a class=\'home-dec\' href=\'kejianshiguang.html\'>课间时光</a> ");
document.writeln("              <!-- 图标开始 --> ");
document.writeln("              <i class=\'iconfont iconJt\'></i> ");
document.writeln("              <!-- 图标结束 -->");
document.writeln("              <div class=\'navSedBox\'>");
document.writeln("                <ul class=\'navSedUl\'>");
document.writeln("                  <li class=\'navYj\'> <i class=\'iconfont backBtn\'></i> 课间时光</li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'BookDetails.html\' class=\'navSedTitLink\'>电子书</a> </h3>");
document.writeln("                  </li>");
document.writeln("                  <li class=\'navSed\'>");
document.writeln("                    <h3 class=\'navSedTit\'> <a href=\'kejianshiguang.html\' class=\'navSedTitLink\'>视频与音乐</a> </h3>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'navContentBox\'>");
document.writeln("                  <div class=\'picBox\'> <img src=\'images/kjsg.jpg\' title=\'\' class=\'navImg\' alt=\'课间时光\'> </div>");
document.writeln("                  <a href=\'/news/2/\' class=\'tit\'>课间时光</a>");
document.writeln("                  <article class=\'navSummray\'></article>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </li>");
document.writeln("            <li class=\'hvr-left subnav2 js-m js-m-2 animate\'> <a class=\'home-dec\' href=\'contact.html\'>联系我们</a> ");
document.writeln("              <!-- 图标开始 --> ");
document.writeln("              <!-- 图标结束 --> ");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("        </nav>");
document.writeln("        <div class=\'RightB\'><a class=\'seach\'><img src=\'images/search_03.png\' alt=\'永胜学院\'></a>");
document.writeln("          <div class=\'login\'><a href=\'login.html\' class=\'dl\'>登录</a><a href=\'zc.html\' class=\'zc\'>注册</a></div>");
document.writeln("          <div class=\'loginH\'><p>您好，测试用户<a href=\'buy.html\' id=\'Integral\'>积分0</a><a id=\'Quit\'>退出</a></p></div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </header>");
document.writeln("  </div>");
document.writeln("  <!--PC导航结束--> ");
document.writeln("  ");
document.writeln("  <!--MO导航-->");
document.writeln("  <div class=\'header2\'>");
document.writeln("    <div class=\'main-wrap f-cb\'>");
document.writeln("      <h1 class=\'logo fl\'> <a href=\'/\'> <img src=\'images/logo_03.png\' alt=\'logo\'> </a> </h1>");
document.writeln("      <div class=\'nav-btn fr\'> <span class=\'line line1\'></span> <span class=\'line line2\'></span> <span class=\'line line3\'></span> </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'sub-menu\'>");
document.writeln("      <ul>");
document.writeln("        <li class=\'js-m-3 delay01\'> <a class=\'tit sub-tit\' href=\'/\'>网站首页</a> </li>");
document.writeln("        <li class=\'js-m-3 delay02\'> <a class=\'tit sub-tit\' href=\'\'>学院概况</a> <i class=\'jt\'></i>");
document.writeln("          <div class=\'sec-list\'>");
document.writeln("            <p> <a href=\'\'>简介</a> </p>");
document.writeln("            <p> <a href=\'\'>组织机构</a> </p>");
document.writeln("            <p> <a href=\'\'>管理层</a> </p>");
document.writeln("          </div>");
document.writeln("        </li>");
document.writeln("        <li class=\'js-m-3 delay03\'> <a class=\'tit sub-tit\' href=\'\'>教学课程</a> <i class=\'jt\'></i>");
document.writeln("          <div class=\'sec-list\'>");
document.writeln("            <p> <a href=\'\'>文学</a> </p>");
document.writeln("            <p> <a href=\'\'>理学</a> </p>");
document.writeln("            <p> <a href=\'\'>外国语言</a> </p>");
document.writeln("            <p> <a href=\'\'>政治学</a> </p>");
document.writeln("            <p> <a href=\'\'>计算机类</a> </p>");
document.writeln("          </div>");
document.writeln("        </li>");
document.writeln("        <li class=\'js-m-3 delay04\'> <a class=\'tit sub-tit\' href=\'\'>课间时光 </a><i class=\'jt\'></i>");
document.writeln("          <div class=\'sec-list\'>");
document.writeln("            <p> <a href=\'\'>休闲小游戏</a> </p>");
document.writeln("            <p> <a href=\'\'>视频与音乐</a> </p>");
document.writeln("          </div>");
document.writeln("        </li>");
document.writeln("        <li class=\'js-m-3 delay05\'> <a class=\'tit sub-tit\' href=\'\'>联系我们</a> </li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <div class=\'search-bg\'></div>");
document.writeln("  <!--MO导航结束--> ");
document.writeln("  <!--SEARCH 弹出层-->");
document.writeln("  <div class=\'c-mask-overlay\'></div>");
document.writeln("  <div class=\'search-alert\'> <span class=\'close iconfont icon-close\'></span>");
document.writeln("    <div class=\'cent-form iconfont icon-search1\'>");
document.writeln("      <form action=\'search_result.html\' method=\'GET\' id=\'pro-ser-frm\'>");
document.writeln("        <input class=\'fl tex\' type=\'text\' id=\'news_search_word\' name=\'keyword\' value=\'\' placeholder=\'请输入搜索内容\' onblur=\'if(!value){value=defaultValue;}\' onfocus=\'if(value==defaultValue){value=\'\';}\'>");
document.writeln("        <input class=\'fr sub-butn\' type=\'submit\' id=\'lv_search\' value=\'ENTER\'>");
document.writeln("      </form>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <!--SEARCH 弹出层结束--> ");
document.writeln("</div>");

$(".seach").click(function(){
  $(".search-alert").css("display","block");
});
$(".search-alert .close").click(function(){
  $(".search-alert").css("display","none");
});



